gemini:
  key: AIzaSyCdW06STYYHCV4OinTCLGs2dpABUnWq0aY
openai:
  key: AIzaSyCdW06STYYHC7599hsogossajjgjsihsioja


patientــName: mehran
age: 19
job: computer developer

results:
  en: ../results/result.md